<a href="https://colab.research.google.com/github/mariettarosemathew-ui/CaseStudy_AcquisitionandETL/blob/main/Casestudy_ETL_Marietta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [3]:
import pandas as pd

In [4]:
filepathcsv='/content/drive/MyDrive/DSA Class/Datasets/population.csv'
df=pd.read_csv(filepathcsv)
df

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [ ]:
df.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [5]:
df.shape

(25, 2)

In [6]:
df.dtypes

country       object
population     int64
dtype: object

Q2

In [7]:
filepathexcel='/content/drive/MyDrive/DSA Class/Datasets/gdp.xlsx'
df=pd.read_excel(filepathexcel)
df

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [8]:
df.columns

Index(['Country', 'GDP'], dtype='object')

In [9]:
df.dtypes

Country    object
GDP         int64
dtype: object

Q3

In [10]:
filepathjson='/content/drive/MyDrive/DSA Class/Datasets/internet_users.json'
df=pd.read_json(filepathjson)
df

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

Q4

In [11]:
filepathxml='/content/drive/MyDrive/DSA Class/Datasets/literacy_rate.xml'
df=pd.read_xml(filepathxml)
df

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Q5

In [12]:
population_df=pd.read_csv(filepathcsv)
gdp_df=pd.read_excel(filepathexcel)
internet_df=pd.read_json(filepathjson)
literacy_df=pd.read_xml(filepathxml)

In [13]:
print("Rows",population_df.shape[0])
print("Columns",population_df.shape[1])
print("Column Name",population_df.columns)
print("data type",population_df.dtypes)
print("missing value",population_df.isnull().sum)
print("duplicate values",population_df.duplicated().sum)

Rows 25
Columns 2
Column Name Index(['country', 'population'], dtype='object')
data type country       object
population     int64
dtype: object
missing value <bound method DataFrame.sum of     country  population
0     False       False
1     False       False
2     False       False
3     False       False
4     False       False
5     False       False
6     False       False
7     False       False
8     False       False
9     False       False
10    False       False
11    False       False
12    False       False
13    False       False
14    False       False
15    False       False
16    False       False
17    False       False
18    False       False
19    False       False
20    False       False
21    False       False
22    False       False
23    False       False
24    False       False>
duplicate values <bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool>

In [14]:
print("Rows",gdp_df.shape[0])
print("Columns",gdp_df.shape[1])
print("Column Name",gdp_df.columns)
print("data type",gdp_df.dtypes)
print("missing value",gdp_df.isnull().sum)
print("duplicate values",gdp_df.duplicated().sum)

Rows 25
Columns 2
Column Name Index(['Country', 'GDP'], dtype='object')
data type Country    object
GDP         int64
dtype: object
missing value <bound method DataFrame.sum of     Country    GDP
0     False  False
1     False  False
2     False  False
3     False  False
4     False  False
5     False  False
6     False  False
7     False  False
8     False  False
9     False  False
10    False  False
11    False  False
12    False  False
13    False  False
14    False  False
15    False  False
16    False  False
17    False  False
18    False  False
19    False  False
20    False  False
21    False  False
22    False  False
23    False  False
24    False  False>
duplicate values <bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool>

In [15]:
print("Rows",internet_df.shape[0])
print("Columns",internet_df.shape[1])
print("Column Name",internet_df.columns)
print("data type",internet_df.dtypes)
print("missing value",internet_df.isnull().sum)
print("duplicate values",internet_df.duplicated().sum)

Rows 25
Columns 2
Column Name Index(['country', 'internet_users'], dtype='object')
data type country           object
internet_users     int64
dtype: object
missing value <bound method DataFrame.sum of     country  internet_users
0     False           False
1     False           False
2     False           False
3     False           False
4     False           False
5     False           False
6     False           False
7     False           False
8     False           False
9     False           False
10    False           False
11    False           False
12    False           False
13    False           False
14    False           False
15    False           False
16    False           False
17    False           False
18    False           False
19    False           False
20    False           False
21    False           False
22    False           False
23    False           False
24    False           False>
duplicate values <bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool>

In [16]:
print("Rows",literacy_df.shape[0])
print("Columns",literacy_df.shape[1])
print("Column Name",literacy_df.columns)
print("data type",literacy_df.dtypes)
print("missing value",literacy_df.isnull().sum)
print("duplicate values",literacy_df.duplicated().sum)

Rows 25
Columns 2
Column Name Index(['name', 'literacy_rate'], dtype='object')
data type name              object
literacy_rate    float64
dtype: object
missing value <bound method DataFrame.sum of      name  literacy_rate
0   False          False
1   False          False
2   False          False
3   False          False
4   False          False
5   False          False
6   False          False
7   False          False
8   False          False
9   False          False
10  False          False
11  False          False
12  False          False
13  False          False
14  False          False
15  False          False
16  False          False
17  False          False
18  False          False
19  False          False
20  False          False
21  False          False
22  False          False
23  False          False
24  False          False>
duplicate values <bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool>

Q6

In [17]:
gdp=gdp_df.rename(columns={"Country":"country"})
literacy=literacy_df.rename(columns={"name":"country"})
print(gdp)
print(literacy)

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000
           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Q7

In [18]:
print("Polulation")
print(population_df.dtypes)
print('\n')
print("GDP")
print(gdp_df.dtypes)
print('\n')
print("Internet")
print(internet_df.dtypes)
print('\n')
print("Literacy")
print(literacy_df.dtypes)

Polulation
country       object
population     int64
dtype: object


GDP
Country    object
GDP         int64
dtype: object


Internet
country           object
internet_users     int64
dtype: object


Literacy
name              object
literacy_rate    float64
dtype: object

Q8

In [21]:
merged_df = pd.merge(population_df, gdp, on="country", how="inner")
merged_df = pd.merge(merged_df, internet_df, on="country", how="inner")
merged_df = pd.merge(merged_df, literacy, on="country", how="inner")

merged_df

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

Q9

In [22]:
merged_df["Internet Penetration (%)"] = ((merged_df["internet_users"] / merged_df["population"]) * 100).round(2)

merged_df["GDP Per Capita"] = (merged_df["GDP"] / merged_df["population"]).round(2)

merged_df

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
6,France,65273511,3211000,62000000,99.0,94.98,0.05
7,Italy,60461826,2420000,56000000,99.0,92.62,0.04
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
11,Russia,145934462,2200000,125000000,99.7,85.65,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
13,Spain,46754778,1710000,44000000,98.6,94.11,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
18,South Africa,59308690,410000,43000000,95.0,72.50,0.01
19,Argentina,45195774,640000,41000000,99.1,90.72,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09

Q10

In [25]:
import sqlite3
conn=sqlite3.connect("country_statistics.db")
merged_df.to_sql("country_statistics", conn, if_exists="replace", index=False)

25

Q11

In [27]:
query = "select*from country_statistics LIMIT 5"
result = pd.read_sql(query, conn)
result

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

Part E

In [28]:
merged_df.nlargest(5, "GDP")[["country", "GDP"]]

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [30]:
merged_df.nlargest(5, "population")[["country", "population"]]

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [31]:
merged_df["literacy_rate"].mean()

np.float64(97.248)

In [32]:
merged_df[merged_df["literacy_rate"] > 90][["country", "literacy_rate"]]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [36]:
merged_df[merged_df["Internet Penetration (%)"] > 70][["country", "Internet Penetration (%)"]]

           country  Internet Penetration (%)
0    United States                     94.26
1            China                     76.50
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
10          Brazil                     85.15
11          Russia                     85.65
12     South Korea                     96.56
13           Spain                     94.11
14          Mexico                     79.11
15       Indonesia                     77.51
16    Saudi Arabia                     97.66
17          Turkey                     81.81
18    South Africa                     72.50
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

In [37]:
merged_df.nlargest(5, "GDP Per Capita")[["country", "GDP Per Capita"]]

          country  GDP Per Capita
21    Switzerland            0.11
23         Norway            0.11
0   United States            0.09
24      Singapore            0.09
9       Australia            0.07

In [38]:
merged_df["population"].sum()

np.int64(4720039725)

In [39]:
merged_df["Internet Penetration (%)"].mean()

np.float64(89.6596)

In [40]:
merged_df.nlargest(1, "internet_users")[["country", "internet_users"]]

  country  internet_users
1   China      1080000000

In [41]:
merged_df["literacy_rate"].corr(merged_df["Internet Penetration (%)"])

np.float64(0.77279756813985)

Part F

In [42]:
query = """
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5
"""

pd.read_sql(query, conn)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [43]:
query = """
SELECT AVG(literacy_rate) AS average_literacy
FROM country_statistics
"""

pd.read_sql(query, conn)

   average_literacy
0            97.248

In [44]:
query = """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90
"""

pd.read_sql(query, conn)

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5

In [45]:
query = """
SELECT country, "Internet Penetration (%)"
FROM country_statistics
ORDER BY "Internet Penetration (%)" DESC
LIMIT 5
"""

pd.read_sql(query, conn)

        country  Internet Penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

In [46]:
query = """
SELECT SUM(population) AS total_population
FROM country_statistics
"""

pd.read_sql(query, conn)

   total_population
0        4720039725

In [47]:
query = """
SELECT country, "GDP Per Capita"
FROM country_statistics
ORDER BY "GDP Per Capita" DESC
LIMIT 1
"""

pd.read_sql(query, conn)

       country  GDP Per Capita
0  Switzerland            0.11

In [48]:
merged_df.to_csv("final_merged_dataset.csv", index=False)

In [49]:
query = """
SELECT *
FROM country_statistics
ORDER BY "GDP Per Capita" DESC
LIMIT 10
"""

pd.read_sql(query, conn)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
1,Norway,5421241,580000,5300000,100.0,97.76,0.11
2,United States,331002651,30500000,312000000,99.0,94.26,0.09
3,Singapore,5850342,530000,5600000,97.5,95.72,0.09
4,Australia,25687041,1880000,24000000,99.0,93.43,0.07
5,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
6,Germany,83240525,4744000,79000000,99.0,94.91,0.06
7,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Sweden,10353442,650000,10100000,99.0,97.55,0.06